# Generated by Django 5.2.7 on 2025-12-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookadsproject',
            old_name='conversion_action_descriptive_name',
            new_name='meta_pixel_access_token',
        ),
        migrations.RenameField(
            model_name='facebookadsproject',
            old_name='conversion_action_resource_name',
            new_name='meta_pixel_id',
        ),
    ]
