"""
Django settings for pixel_tracker project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jc%(xiv1oiio6eg4c_6#)14j8bp+c^+=^-t+kitms0gozz86^c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    "Content-Type",
    "Authorization",
    "ngrok-skip-browser-warning",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'facebook_ads',
    'google_ads',
    'hubspot',
    'tracker',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pixel_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pixel_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Simple JWT Token Expiration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # access token valid 5 mins
    'REFRESH_TOKEN_LIFETIME': timedelta(days=180),   # refresh token valid 1 day
}


# Email configuration
PUBLIC_BASE_URL = "http://qla.zipeline.com/accounts"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "ops@growthspree.in")
# App password expected when using Gmail with 2FA enabled.
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "fyzk leai mgdx aaom")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Zipeline Tracker<ops@growthspree.in>")


#Common Config for All Integrations
#REDIRECT_URI = "https://tracker.zipeline.com/integrations"
REDIRECT_URI = "https://qla.zipeline.com/integrations"
#REDIRECT_URI = "https://birbal.ngrok.dev/integrations"

# Facebook Ads
FB_APP_ID="804648675705400"
FB_APP_SECRET="10bc2549e1a3f4e8a4db7dce7e2ce299"

# Google Ads/Analytics/Search Console
GOOGLE_CLIENT_SECRET_PATH = "/home/ubuntu/qla-backend/secrets.json"
#GOOGLE_CLIENT_SECRET_PATH = r"C:\Kushagra\pixel_tracker\secrets.json"
GOOGLE_CLIENT_ID = "924396653230-rdq72k39pk9k5pckmjtsg0gkrd2fofd9.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_DEVELOPER_TOKEN = "rnBUQcH_QfearOChXO-1yQ"



HUBSPOT_APP_ID=24342734
HUBSPOT_CLIENT_ID="c710bdd7-778f-4c4f-81b8-161522f4b87e"
HUBSPOT_CLIENT_SECRET="7fb0a384-d9f2-46bf-a2dd-a1fe3b8cfb06"
HUBSPOT_REDIRECT_URI="https://qla.zipeline.com/integrations"
HUBSPOT_OAUTH_SCOPES="crm.objects.contacts.read crm.objects.companies.read crm.objects.deals.read crm.objects.leads.read crm.objects.users.read settings.users.read oauth"


CRON_SECRET_KEY="f3c4d5c0d0e7724b4b60e3c8972f51d2dfe1d3b74cb5a2d199bc884f1c6b8d90"


SNITCHER_RADAR_API_KEY="511|E2434QIIwDUYauvxr0NsD37QWg01sfgU1vXuJo24849fb401"

SNITCHER_TRACKER_API_URL="https://api.snitcher.com/radar/operator/v1/tracking-scripts"


# Moolya
# <script>!function(e,t,r,a,n){var p=t.getElementsByTagName(r)[0],c=t.createElement(r);c.async=!0,c.src=a+"?id="+n,p.parentNode.insertBefore(c,p)}(window,document,"script","https://ip-tracker-blond.vercel.app/api/pixel.js","98862d50-099d-4517-843c-ecacfe73ac9b");</script>


# Craze
# <script>!function(e,t,r,a,n){var p=t.getElementsByTagName(r)[0],c=t.createElement(r);c.async=!0,c.src=a+"?id="+n,p.parentNode.insertBefore(c,p)}(window,document,"script","https://ip-tracker-blond.vercel.app/api/pixel.js","e27f0dd2-6c7c-4a28-abe5-1b795a492592");</script>
