# Generated by Django 5.2.7 on 2025-12-02 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAdsProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_token", models.CharField(max_length=500)),
                ("customer_id", models.CharField(max_length=500)),
                ("customer_name", models.CharField(blank=True, max_length=500)),
                (
                    "conversion_action_resource_name",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "conversion_action_descriptive_name",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
