# Generated by Django 5.2.7 on 2025-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleadsproject",
            name="manager_id",
            field=models.IntegerField(default=0),
        ),
    ]
