# Generated by Django 5.2.7 on 2025-12-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_ads", "0002_googleadsproject_manager_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleadsproject",
            name="Conversion_action_category",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
