# Generated by Django 5.2.7 on 2025-12-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google_ads", "0003_googleadsproject_conversion_action_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googleadsproject",
            old_name="Conversion_action_category",
            new_name="Conversion_action_category_name",
        ),
    ]
