# Generated by Django 5.2.7 on 2025-12-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "google_ads",
            "0004_rename_conversion_action_category_googleadsproject_conversion_action_category_name",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="googleadsproject",
            old_name="Conversion_action_category_name",
            new_name="conversion_action_category_name",
        ),
    ]
