# Generated by Django 5.2.7 on 2025-12-02 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IpInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Found", max_length=255)),
                ("click_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("employees", models.CharField(blank=True, max_length=255, null=True)),
                ("revenue", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "conversion_status",
                    models.CharField(
                        choices=[
                            ("Sent", "Sent"),
                            ("Not Sent", "Not Sent"),
                            ("Expired", "Expired"),
                            ("Processing", "Processing"),
                        ],
                        default="Processing",
                        max_length=20,
                    ),
                ),
                ("url_visited", models.URLField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("utm_id", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("user_agent", models.CharField(max_length=255)),
                ("device_type", models.CharField(max_length=255)),
                ("url_visited", models.URLField()),
                ("event_properties", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.company",
                    ),
                ),
            ],
        ),
    ]
