# Generated by Django 5.2.7 on 2025-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="url_visited",
            field=models.URLField(max_length=800),
        ),
        migrations.AlterField(
            model_name="companyvisit",
            name="url_visited",
            field=models.URLField(max_length=800),
        ),
    ]
