# Generated by Django 5.2.7 on 2025-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_company_url_visited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="technologies",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
