# Generated by Django 5.2.7 on 2025-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_company_categories_company_company_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
